# Generated by Django 6.0.7 on 2026-07-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('watering', models.CharField(max_length=200)),
                ('sunlight', models.CharField(max_length=200)),
                ('soil', models.CharField(max_length=200)),
                ('fertilizer', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
