# Generated by Django 6.0.7 on 2026-07-22 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_schedule_wateringreminder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('schedule_date', models.DateField()),
                ('schedule_time', models.TimeField()),
                ('repeat', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user')),
            ],
        ),
    ]
