# Generated by Django 6.0.7 on 2026-07-23 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_schedulereminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wateringreminder',
            name='created_at',
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='is_watered',
            field=models.BooleanField(default=False),
        ),
    ]
