# Generated by Django 6.0.7 on 2026-07-23 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_wateringreminder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='done_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='watered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
