# Generated by Django 6.0.7 on 2026-07-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_schedule_done_on_schedule_is_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereminder',
            name='done_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulereminder',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
