# Generated by Django 6.0.7 on 2026-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_schedulereminder_done_on_schedulereminder_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='page',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
