# Generated by Django 6.0.7 on 2026-07-25 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_favoriteplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='Plant Lover', max_length=50),
        ),
    ]
