# Generated by Django 6.0.7 on 2026-07-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_passwordresettoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wateringreminder',
            old_name='watering_date',
            new_name='reminder_date',
        ),
        migrations.RenameField(
            model_name='wateringreminder',
            old_name='watering_time',
            new_name='reminder_time',
        ),
        migrations.RemoveField(
            model_name='wateringreminder',
            name='is_watered',
        ),
        migrations.RemoveField(
            model_name='wateringreminder',
            name='plant_name',
        ),
        migrations.RemoveField(
            model_name='wateringreminder',
            name='watered_on',
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='plant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.plant'),
        ),
        migrations.AlterField(
            model_name='wateringreminder',
            name='repeat',
            field=models.CharField(default='One Time', max_length=50),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
