# Generated by Django 6.0.7 on 2026-07-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_rename_watering_date_wateringreminder_reminder_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wateringreminder',
            old_name='reminder_date',
            new_name='watering_date',
        ),
        migrations.RenameField(
            model_name='wateringreminder',
            old_name='reminder_time',
            new_name='watering_time',
        ),
        migrations.RemoveField(
            model_name='wateringreminder',
            name='plant',
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='is_watered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='plant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='watered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wateringreminder',
            name='repeat',
            field=models.CharField(default="Doesn't Repeat", max_length=30),
        ),
    ]
