# Generated by Django 6.0.7 on 2026-07-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_rename_reminder_date_wateringreminder_watering_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
