# Generated by Django 6.0.7 on 2026-07-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereminder',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
