# Generated by Django 6.0.7 on 2026-07-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_schedulereminder_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_scan_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
