# Generated by Django 6.0.7 on 2026-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_user_ai_scan_count_user_ai_scan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulereminder',
            name='missed_popup_shown',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wateringreminder',
            name='missed_popup_shown',
            field=models.BooleanField(default=False),
        ),
    ]
